name: Rust
  # You may pin to the exact commit or the version.
  # uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 
    
    - name: checkout version
      uses: actions/checkout@v2
    - name: rust-cargo
      uses: actions-rs/cargo@v1.0.1
      with: 
        # Cargo command to run (ex. `check` or `build`)
        command: 
          skyline build
    #- uses: actions/checkout@v3
    #- name: Build
      #run: cd scripts && python3 build.py
