name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 
    
    - name: checkout version
      uses: actions/checkout@v2
    
    - uses: actions/checkout@v3
    - name: Build
      run: cd scripts && python3 build.py
