name: rust_build
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pr_build:
    env:
      PLUGIN_NAME: plugin
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 
    
    - name: checkout version
      uses: actions/checkout@v2

    # build the project
    - run: |
        export PATH=$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin \
        && cd scripts && python3 build.py
      env:
        HOME: /root
    - name: Upload plugin
      uses: actions/upload-artifact@v3
      env:
        HOME: /root
      with:
        name: Ultimate S Arcropolis
        path: releases
  upload:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - pr_build
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    - name: Update Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allow_override: true
        gzip: false
        tag: nightly
        name: Nightly
        body: >
          Nightly built off of the latest code in the repository. Probably unstable
        files: >
          * 
