name: rust_build
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pr_build:
    env:
      PLUGIN_NAME: plugin
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 
    
    - name: checkout version
      uses: actions/checkout@v2

    # build the project
    - run: |
        export PATH=$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin \
        && cd scripts && python3 build.py
      env:
        HOME: /root
    - name: Upload plugin
      uses: actions/upload-artifact@v3
      env:
        HOME: /root
      with:
        name: Ultimate S Arcropolis
        path: releases
  upload_release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - pr_build
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        # Artifact name
        name: Ultimate S Acropolis
    - name: releases-action
      uses: nickatnight/releases-action@v2
      with:
        # Name of branch to release from
        branch: main
        # Name of the release
        name: Nightly
        # Message for the release
        message: Nightly build containing the latest code from the repository. May be unstable.
        # Pre-release or naw
        prerelease: true
        # Name of tag
        tag: nightly
  
