name: rust_build
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr_build:
    env:
      PLUGIN_NAME: plugin
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 
    
    - name: checkout version
      uses: actions/checkout@v2

    # build the project
    - run: |
        cd scripts && python3 build.py
      env:
        HOME: /root
    - name: Upload plugin
      uses: actions/upload-artifact@v3
      env:
        HOME: /root
      with:
        name: plugin
        path: releases
